trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
     - task: NodeTool@0
       displayName: 'Install Node.js'
       inputs:
         versionSpec: '12.x'

     - script: |
        npm install -g @angular/cli
        npm install 
       displayName: 'install dependencies' 

     - task: AzureCLI@2
       displayName: 'Clear Static website'
       inputs:
         azureSubscription: 'sow-angular-service-connection'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: 'az storage blob delete-batch --account-name angularstoragedev --source "\$web"'
     - task: AzureCLI@2
       displayName: 'Upload new Static Website'
       inputs:
         azureSubscription: 'sow-angular-service-connection'
         scriptType: 'bash'
         scriptLocation: 'inlineScript' 
         inlineScript: 'az storage blob upload-batch --account-name angularstoragedev --destination "\$web" --source ''$(Build.Repository.LocalPath)/dist/angular'''




 

