trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
 inputs:
   versionSpec: '12.x'
 displayName: 'Install Node.js'

- script: |
   npm install -g @angular/cli
   npm install 
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'npm install'


- script: npm run lint
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'Lint Angular'

- script: npm run build --prod
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'npm build'

- script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'npm test'

- publish: $(System.DefaultWorkingDirectory)/site/dist
 artifact: angular-app

- publish: $(System.DefaultWorkingDirectory)/arm-templates
 artifact: arm-templates