trigger:
- main

pool:
 vmImage: 'Azure Pipelines'
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
    - Dev
  

stages:
 -stage:'BuildTest'
  displayName:'Build & Test'
  jobs:
   -job:'build'
   displayName:'Build artifacts'
   steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '12.x'

    - script: |
        npm install -g @angular/cli
        npm install 
        displayName: 'install dependencies'


- script: npm run lint
 displayName: 'Lint Angular'

- script: npm run build --prod
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'npm build'

- script: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
 workingDirectory: $(Build.SourcesDirectory)/site
 displayName: 'npm test'

- publish: $(System.DefaultWorkingDirectory)/site/dist
 artifact: angular-app

- publish: $(System.DefaultWorkingDirectory)/arm-templates
 artifact: arm-templates