trigger:
- main

pool:
 vmImage: 'Azure Pipelines'
parameters:
  - name: environment
    displayName: Environment
    type: string
    default: Dev
    values:
    - Dev

stages:
- stage: 'BuildTest'
  displayName:'Build & Test'
  jobs:
  - job: build
    steps:
      -task: NodeTool@0
       displayName: 'Install Node.js'
       inputs:
        versionSpec: '11.x'
        
- stage: 'BuildTest'
 

